Bundler/OrderedGems:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "Gemfile"
    - "Rakefile"
    - "db/schema.rb"
  SuggestExtensions: false
  NewCops: disable
